"""
Django settings for root project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import dj_database_url
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dummy-key')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://*.up.railway.app',
    'https://web-production-77d7e.up.railway.app'
]

# Also ensure these are set for Railway's HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #Apps
    'crm',
    'finance',
    'frontdesk',
    'inventory',
    'users',
    #REST FRAMEWORK AND AUTHENTICATION
    'rest_framework',
    'djoser',
    'rest_framework_simplejwt',
    #DOCS
    'drf_spectacular',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'root.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'root.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

""" DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
} """
DATABASES = {
    'default': dj_database_url.config(default='sqlite:///db.sqlite3')
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

#STATIC_URL = '/static/'
#STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#JAZZMINE_SETTINGS
JAZZMIN_SETTINGS = {
    "site_title": "Styalar PMS",
    "site_header": "Styalar",
    "site_brand": "Styalar PMS",
    "site_logo": "images/logo.svg",  # This handles the 'A' logo
    "login_logo": "images/logo.svg", # This handles the login page logo
    "welcome_sign": "Welcome to Styalar PMS",
    "copyright": "Styalar Hotel Group",
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://your-support-link.com", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    # Icons make the PMS look modern (using FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-circle",
        "auth.group": "fas fa-user-lock",
        
        # CRM Icons
        "crm.Guest": "fas fa-user-tie",
        "crm.Organization": "fas fa-building",
        "crm.Country": "fas fa-globe-asia",
        "crm.ArAccount": "fas fa-file-invoice-dollar",
        "crm.Gender": "fas fa-venus-mars",
        
        # Frontdesk Icons
        "frontdesk.Reservation": "fas fa-calendar-check",
        "frontdesk.Source": "fas fa-share-alt",
        "frontdesk.ReservationRequest": "fas fa-sitemap",
        
        # Inventory Icons
        "inventory.Property": "fas fa-hotel",
        "inventory.Room": "fas fa-door-open",
        "inventory.RoomType": "fas fa-layer-group",
        "inventory.Floor": "fas fa-layer-group",
        "inventory.AddOnItem": "fas fa-list",
        "inventory.Attribute": "fas fa-puzzle-piece",
        "inventory.Exposure": "fas fa-chart-area",
        "inventory.BedType": "fas fa-bed",
        "inventory.Building": "fas fa-city",
        "inventory.RoomTypeBed": "fas fa-list",
        "inventory.Zone": "fas fa-map-marked-alt",
        
        # Finance Icons
        "finance.RatePlan": "fas fa-tags",
        "finance.MarketSegment": "fas fa-chart-pie",
        "finance.RoomRate": "fas fa-percent",

        #Users
        "users.User": "fas fa-users"
    },
    # This ensures models without an icon still look clean
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "custom_css": "css/custom_admin.css",
    "site_logo_classes": "",
}

JAZZMIN_UI_TWEAKS = {
    # Navbar: Pure white for a clean top look
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,

    # Sidebar: Light gray/white theme (instead of dark)
    "sidebar": "sidebar-light-primary", 
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    
    # Theme & Accent: Using a professional blue
    "theme": "faltly",
    "accent": "accent-primary",
    
    # Button and Brand styles
    "brand_colour": "navbar-primary",
    "brand_small_text": False,
}
JET_THEMES = [
    {
        'theme': 'dark-blue', 
        'color': '#3b82f6',   
        'title': 'Styalar Blue'
    },
    {
        'theme': 'default', # The original green
        'color': '#44b78b',
        'title': 'Default Green'
    },
]
JET_DEFAULT_THEME = 'dark-blue'
AUTH_USER_MODEL = 'users.User'