# Generated by Django 5.2.4 on 2025-12-29 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='market_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.marketsegment'),
        ),
    ]
