# Generated by Django 5.2.4 on 2025-12-29 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('finance', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reservation_number', models.CharField(max_length=20, unique=True)),
                ('reservation_type', models.CharField(choices=[('reserved', 'Reserved'), ('checked-in', 'Checked-In'), ('in-house', 'In-House'), ('checked-out', 'Checked-Out'), ('cancelled', 'Cancelled')], default='reserved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_created', to=settings.AUTH_USER_MODEL)),
                ('market_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.marketsegment')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.organization')),
                ('primary_guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_reservations', to='crm.guest')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.rateplan')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.room')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.roomtype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.guest')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontdesk.reservation')),
            ],
            options={
                'unique_together': {('reservation', 'guest')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.ManyToManyField(related_name='reservations', through='frontdesk.ReservationGuest', to='crm.guest'),
        ),
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('posting_schedule', models.CharField(choices=[('EACH_DAY', 'Each Day'), ('ONCE', 'Once')], max_length=20)),
                ('folio_target', models.CharField(choices=[('GUEST', 'Guest'), ('ORG', 'Organization')], max_length=20)),
                ('include_in_package', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.addonitem')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='frontdesk.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frontdesk.source'),
        ),
    ]
